---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kavita
  labels:
    app: kavita
spec:
  selector:
    matchLabels:
      app: kavita-pod
  template:
    metadata:
    spec:
      containers:
        - name: kavita
          hostname: kavita
          image: jvmilazz0/kavita:0.8.4
          restartPolicy: unless-stopped
          volumeMounts:
            - mountPath: /kavita/config
              name: kavita_data
            - mountPath: /books
              name: books
            - mountPath: /manga
              name: manga

      volumes:
        - name: kavita_data
          persistentVolumeClaim:
            claimName: kavita-data
        - name: books
          hostPath:
            path: /mnt/media/books
            type: Directory
        - name: manga
          hostPath:
            path: /mnt/media/manga
            type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kavita-data
spec:
  storageClassName: manual
  accessMode:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
