name: Renovate Container Images

on:
  # Run weekly on Monday at 9 AM UTC
  schedule:
    - cron: '0 9 * * 1'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/renovate-action@v40
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
