apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-configmap
data:
  config.alloy: |
    loki.source.syslog "syslog_listen" {
      listener {
        address = "0.0.0.0:60514"
        protocol = "udp"
        labels = { component = "loki.source.syslog" }
        syslog_format = "rfc3164"
        use_rfc5424_message = false
      }

      relabel_rules = loki.relabel.syslog_label.rules
      forward_to = [loki.write.syslog_write.receiver]
    }

    loki.relabel "syslog_label" {
      forward_to = []

      rule {
        source_labels = ["__syslog_message_severity"]
        target_label  = "severity"
      }

      rule {
        source_labels = ["__syslog_message_hostname"]
        target_label  = "hostname"
      }

      rule {
        source_labels = ["__syslog_message_app_name"]
        target_label  = "appname"
      }

      rule {
        source_labels = ["__syslog_message_proc_id"]
        target_label  = "procid"
      }

      rule {
        source_labels = ["__syslog_message_msg_id"]
        target_label  = "msgid"
      }
    }

    loki.write "syslog_write" {
      endpoint {
        url = "http://loki:3100/loki/api/v1/push"
      }
    }

    logging {
      level  = "info"
      format = "logfmt"
    }
