apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-configmap
data:
  local-config.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    common:
      instance_addr: 127.0.0.1
      path_prefix: /loki
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    schema_config:
      configs:
        - from: 2025-08-27
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    limits_config:
      retention_period: 336h
      deletion_mode: "filter-and-delete"

    compactor:
      compaction_interval: 2h
      retention_enabled: true
      retention_delete_delay: 2h
      delete_request_store: "filesystem"
      retention_delete_worker_count: 150

    analytics:
      reporting_enabled: false
