---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  selector:
    matchLabels:
      app: nextcloud-pod
  template:
    metadata:
    spec:
      containers:
        # MariaDB
        - name: mariadb
          hostname: mariadb
          image: docker.io/library/mariadb:11.8.3
          env:
            - name: MYSQL_DATABASE
              value: nextcloud
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: homelab-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: homelab-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: homelab-secrets
                  key: MYSQL_ROOT_PASSWORD
          restartPolicy: unless-stopped
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadb_data

        - name: valkey
          hostname: valkey
          image: docker.io/valkey/valkey:8.1.3-alpine
          args:
            - valkey-server
            - /etc/valkey/valkey.conf
          volumeMounts:
            - mountPath: /data
              name: valkey_data
            - mountPath: /etc/valkey
              name: valkey_conf

        # Nextcloud
        - name: nextcloud
          image: docker.io/library/nextcloud:31.0.8-apache
          args:
            - apache2-foreground
          env:
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: 10.89.0.0/24 nextcloud.kanbaru.home
            - name: PHP_MEMORY_LIMIT
              value: 3G
            - name: PHP_UPLOAD_LIMIT
              value: 5G
            # Mariadb env
            - name: MYSQL_DATABASE
              value: nextcloud
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: homelab-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: homelab-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: homelab-secrets
                  key: MYSQL_HOST
            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: homelab-secrets
                  key: NEXTCLOUD_ADMIN_USER
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: homelab-secrets
                  key: NEXTCLOUD_ADMIN_PASSWORD
            # Valkey env
            - name: REDIS_HOST
              value: valkey
            - name: REDIS_PORT
              value: 6379
          restartPolicy: unless-stopped
          volumeMounts:
            - mountPath: /var/www/html
              name: nextcloud_appdata
            - mountPath: /var/www/html/data
              name: nextcloud_data

      volumes:
        - name: nextcloud_appdata
          # nextcloud persistent data
          persistentVolumeClaim:
            claimName: nextcloud-appdata
        - name: nextcloud_data
          # actual files stored by users
          hostPath:
            path: /home/admintom/podman/nextcloud_data
            type: DirectoryOrCreate
        - name: mariadb_data
          persistentVolumeClaim:
            claimName: mariadb-data
        - name: valkey_data
          persistentVolumeClaim:
            claimName: valkey-data
        - name: valkey_conf
          configMap:
            name: valkey-configmap
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-data
spec:
  storageClassName: manual
  accessMode:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valkey-data
spec:
  storageClassName: manual
  accessMode:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-appdata
spec:
  storageClassName: manual
  accessMode:
    - ReadWriteOnce
