---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pigallery
  labels:
    app: pigallery
spec:
  selector:
    matchLabels:
      app: pigallery-pod
  template:
    metadata:
    spec:
      containers:
        - name: pigallery
          hostname: pigallery
          image: docker.io/bpatrik/pigallery2:2.0.0
          env:
            - name: NODE_ENV
              value: production
          restartPolicy: unless-stopped
          volumeMounts:
            - mountPath: /app/data/config
              name: pigallery_config
            - mountPath: /app/data/db
              name: pigallery_db
            - mountPath: /app/data/tmp
              name: pigallery_tmp
            - mountPath: /app/data/images
              name: photos
              readOnly: true

      volumes:
        - name: pigallery_config
          persistentVolumeClaim:
            claimName: pigallery-config
        - name: pigallery_db
          persistentVolumeClaim:
            claimName: pigallery-db
        - name: pigallery_tmp
          emptyDir:
            sizeLimit: 500Mi
        - name: photos
          hostPath:
            path: /mnt/media/photos
            type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pigallery2-config
spec:
  storageClassName: manual
  accessMode:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pigallery2-db
spec:
  storageClassName: manual
  accessMode:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
