---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
    spec:
      containers:
        - name: nginx
          hostname: nginx
          image: docker.io/nginx:1.28.0
          restartPolicy: unless-stopped
          volumeMounts:
            - mountPath: /etc/nginx
              name: nginx_data
          ports:
            - containerPort: 80
              hostPort: 8080
      volumes:
        - name: nginx_data
          # Temporary hostPath, for testing purposes
          hostPath:
            path: /home/admintom/containers-homelab/nginx/nginx_data
            type: DirectoryOrCreate
