---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  labels:
    app: jellyseerr
spec:
  selector:
    matchLabels:
      app: jellyseerr-pod
  template:
    metadata:
    spec:
      containers:
        - name: jellyseerr
          hostname: jellyseerr
          image: docker.io/fallenbagel/jellyseerr:2.5.1
          restartPolicy: unless-stopped
          volumeMounts:
            - name: jellyseerr_data
              mountPath: /app/config
          env:
            - name: TZ
              value: Europe/Prague

      volumes:
        - name: jellyseerr_data
          persistentVolumeClaim:
            claimName: jellyseerr-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-data
spec:
  storageClassName: manual
  accessMode:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
